user_setOne:
    path:     /{id}/
    defaults: { _controller: "UserBundle:User:setOne" }
    methods:  [POST,GET]
    requirements:
        id: \d+
user_setAll:
    path:     /
    defaults: { _controller: "UserBundle:User:getAll" }
    methods:  [GET]
    

