user_setOne:
    path:     /{id}/
    defaults: { _controller: "UserBundle:User:setOne" }
    methods:  [POST]
    requirements:
        id: \d+
user_setAll:
    path:     /
    defaults: { _controller: "UserBundle:User:setAll" }
    methods:  [GET]
    

