user_getOne:
    path:     /{id}/
    defaults: { _controller: "UserBundle:User:getOne" }
    methods:  [GET,POST]
    requirements:
        id: \d+
user_getAll:
    path:     /
    defaults: { _controller: "UserBundle:User:getAll" }
    methods:  [GET]
