framework:
    templating:
        engines: ['pug','mustache','html']
    compression_gzip: true
    bundles:
        UserBundle: { 
            templating: mustache,
            prefix: /user
        }  
    
services:
    
    #CACHE ['mongo','file','memory','redis']
    db:
        params:
    ws:
        params: 
            cache_type : memory
            port: 8098  
            access_control:    
                -  { path: /user/.* , roles: [ROLE_ADMIN] , auth: api_area , whiteip:[192.168.0.11]  }
    longpolling:
        params: 
            cache_type : file
            path: /event/
                
    polling:
        params: 
            cache_type : memory
            path: /polling/
                
private_services:       
    apikey_authenticator:
        class:  UserBundle/Security/ApiKeyAuthenticator
    apikey_userprovider:
        class:  UserBundle/Security/ApiKeyUserProvider   
        
       
security:
    index: home.html

    auth:
        api_area:
            stateless: false
            authenticator: apikey_authenticator
            provider: apikey_userprovider
            
            
    access_control:
             -  { path: (.)*.(asp|aspx|php|jar|java|yml) , roles: DENY_ALL }
             -  { path: /admin/login.html                , roles: IS_AUTHENTICATED_ANONYMOUSLY , whiteip:[192.168.0.11]}
             -  { path: /admin/login_check               , roles: IS_AUTHENTICATED_ANONYMOUSLY , whiteip:[192.168.0.11] }
             -  { path: /admin/.*                        , roles: [ROLE_ADMIN]                 , whiteip:[192.168.0.11], auth: api_area  }
             #-  { path: /user/.*                         , roles: [ROLE_API]                   , auth: api_area }
             -  { path: /.*                              , roles: IS_AUTHENTICATED_ANONYMOUSLY }

