restrict: [
    (.)*.(asp|aspx|php|jar|java|yml),
    /include/(.)*.(css|js)
]
index: home.html
bundles:
    UserBundle: \UserBundle\
        
role_hierarchy:
     ROLE_ADMIN:  [ROLE_ADMIN]
     
access_control:
     -  { path: /admin/login.html  , roles: IS_AUTHENTICATED_ANONYMOUSLY }
     -  { path: /admin/login_check , roles: IS_AUTHENTICATED_ANONYMOUSLY }
     -  { path: /admin/.*          , roles: [ROLE_ADMIN] }
     -  { path: /.*                , roles: IS_AUTHENTICATED_ANONYMOUSLY }